image: rvancea/maven-chrome-jdk8:latest

build-job:
  stage: build
  script:
    - cd Presentables
    - cd license plate recognition
    - mvn compile 


test-job1:
  stage: test
  script:
    - mvn test

  






