image: rvancea/maven-chrome-jdk8:latest

build-job:
  stage: build
  script:
    - cd "/Presentables/license plate recognition"
    - mvn compile 

test-job1:
  stage: test
  script:
    - mvn test

sonarqube:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20
    
sonarqube:
    stage: sonarqube
    script: 
    - cd Presentables
    - cd CertioremSean
    - cd SeansInterface
    - mvn sonar:sonar "-Dsonar.login=e68dd7747d2becfa7ad26c0bed24651e22549497"
  





